#!/usr/bin/env python3
"""Analyze the frozen V70 answer-level profile projection shadow."""

import argparse, hashlib, json, statistics
from pathlib import Path
from run_profile_answer_generalization_v70 import CONDITIONS

ROOT=Path(__file__).resolve().parent
PREREG=ROOT/"configs/profile_answer_generalization_v70_preregistration.json"; DATASET=ROOT/"datasets/profile_answer_generalization_v70.json"; LOCK=ROOT/"configs/profile_answer_generalization_v70_harness_lock.json"; RAW=ROOT/"reports/profile_answer_generalization_v70_raw.json"; ANALYSIS=ROOT/"reports/profile_answer_generalization_v70_analysis.json"; MD=ROOT/"reports/profile_answer_generalization_v70_analysis.md"; RESULT=ROOT/"configs/profile_answer_generalization_v70_result_lock.json"

def load(p): return json.loads(p.read_text(encoding="utf-8"))
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def div(a,b): return a/b if b else 1.0
def p95(v): return sorted(v)[min(len(v)-1,max(0,int(len(v)*.95+.999999)-1))]
def score(row, case):
    reply=str(row["reply"]); expected=case["expected"]; groups=expected["required_marker_groups"]
    hits=[any(str(marker) in reply for marker in group) for group in groups]
    forbidden=[term for term in expected["forbidden_terms"] if term in reply]
    return {"case_id":case["id"],"family":case["scenario_family"],"condition":row["condition"],"memory_relevant":expected["memory_relevant"],"abstention":expected["abstention_required"],"required_hits":sum(hits),"required_count":len(hits),"forbidden_hits":forbidden,"case_pass":all(hits) and not forbidden,"surface_pass":row["surface_gate_pass"],"projection_seconds":row["projection_seconds"],"turn_seconds":row["turn_seconds"],"reply":reply}
def aggregate(rows):
    relevant=[r for r in rows if r["memory_relevant"]]; irrelevant=[r for r in rows if not r["memory_relevant"]]; abstain=[r for r in rows if r["abstention"]]
    return {"case_count":len(rows),"overall_pass_count":sum(r["case_pass"] for r in rows),"relevant_pass_count":sum(r["case_pass"] for r in relevant),"required_marker_group_recall":div(sum(r["required_hits"] for r in rows),sum(r["required_count"] for r in rows)),"stale_or_forbidden_term_case_count":sum(bool(r["forbidden_hits"]) for r in rows),"irrelevant_profile_intrusion_count":sum(bool(r["forbidden_hits"]) for r in irrelevant),"abstention_pass_count":sum(r["case_pass"] for r in abstain),"surface_gate_pass_count":sum(r["surface_pass"] for r in rows),"median_projection_seconds":statistics.median(r["projection_seconds"] for r in rows),"median_full_turn_seconds":statistics.median(r["turn_seconds"] for r in rows),"p95_full_turn_seconds":p95([r["turn_seconds"] for r in rows])}
def analyze(raw,dataset,prereg):
    cases={c["id"]:c for c in dataset["cases"]}; scores=[score(r,cases[r["case_id"]]) for r in raw["rows"]]; metrics={c:aggregate([r for r in scores if r["condition"]==c]) for c in CONDITIONS}; maps={c:{r["case_id"]:r for r in scores if r["condition"]==c} for c in CONDITIONS}; t=maps[CONDITIONS[2]]; a=maps[CONDITIONS[1]]; s=maps[CONDITIONS[0]]
    new_a=sum(t[k]["case_pass"] and not a[k]["case_pass"] for k in t); reg_a=sum(a[k]["case_pass"] and not t[k]["case_pass"] for k in t); new_s=sum(t[k]["case_pass"] and not s[k]["case_pass"] for k in t); m=metrics[CONDITIONS[2]]; g=prereg["treatment_success_gates"]
    checks={"relevant":m["relevant_pass_count"]>=g["relevant_case_pass_count_min"],"overall":m["overall_pass_count"]>=g["overall_case_pass_count_min"],"marker_recall":m["required_marker_group_recall"]>=g["required_marker_group_recall_min"],"forbidden":m["stale_or_forbidden_term_case_count"]<=g["stale_or_forbidden_term_case_count_max"],"intrusion":m["irrelevant_profile_intrusion_count"]<=g["irrelevant_profile_intrusion_count_max"],"abstention":m["abstention_pass_count"]>=g["abstention_pass_count_min"],"new_vs_append":new_a>=g["newly_passed_vs_append_only_min"],"regressions":reg_a<=g["regressions_vs_append_only_max"],"new_vs_session":new_s>=g["newly_passed_vs_session_only_min"],"surface":m["surface_gate_pass_count"]+g["surface_gate_regression_vs_session_only_max"]>=metrics[CONDITIONS[0]]["surface_gate_pass_count"],"projection":m["median_projection_seconds"]<=g["median_projection_seconds_max"],"median_turn":m["median_full_turn_seconds"]<=g["median_full_turn_seconds_max"],"p95_turn":m["p95_full_turn_seconds"]<=g["p95_full_turn_seconds_max"],"transport":raw["transport_error_count"]<=g["transport_error_count_max"],"production":raw["production_database_access_count"]<=g["production_database_access_count_max"],"physical":raw["physical_action_count"]<=g["physical_action_count_max"]}
    integrity={"rows":raw["row_count"]==72 and len(raw["rows"])==72,"pairs":len({(r["case_id"],r["condition"]) for r in raw["rows"]})==72,"conditions":raw["conditions"]==list(CONDITIONS),"locked_preflight":raw["locked_preflight"]["passed"] is True and raw["locked_preflight"]["observed_test_count"]==raw["locked_preflight"]["expected_test_count"],"gold_absent":raw["gold_in_raw"] is False,"temp":all(r["temporary_database"] for r in raw["rows"]),"rightbrain_model_off":raw["rightbrain_model_loading"] is False}
    passed=all(checks.values()) and all(integrity.values()); return {"schema":"uruha_profile_answer_generalization_analysis_v70","decision":"authorize_answer_path_shadow" if passed else "freeze_and_keep_profile_out_of_answers","run_integrity":{"passed":all(integrity.values()),"checks":integrity},"metrics":metrics,"pairwise":{"newly_passed_vs_append_only":new_a,"regressions_vs_append_only":reg_a,"newly_passed_vs_session_only":new_s},"success_gates":{"passed":all(checks.values()),"checks":checks},"treatment_case_scores":list(t.values()),"evidence_boundary":prereg["causal_boundary"]}
def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--write",action="store_true"); args=ap.parse_args(); report=analyze(load(RAW),load(DATASET),load(PREREG))
    if args.write:
        ANALYSIS.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); lines=["# V70 跨 session profile 最終回答結果","",f"**決策：** `{report['decision']}`","","| 條件 | 全體通過 | 記憶相關通過 | 禁用詞案例 | 拒絕猜測 | 中位整輪 |","|---|---:|---:|---:|---:|---:|"]
        for c in CONDITIONS:
            m=report["metrics"][c]; lines.append(f"| {c} | {m['overall_pass_count']}/24 | {m['relevant_pass_count']}/16 | {m['stale_or_forbidden_term_case_count']} | {m['abstention_pass_count']}/4 | {m['median_full_turn_seconds']:.3f}s |")
        lines += ["",f"相對 append-only：新增 {report['pairwise']['newly_passed_vs_append_only']}，退步 {report['pairwise']['regressions_vs_append_only']}。","", "只測臨時資料庫中的完整聊天回答；未授權正式回答使用。"]
        MD.write_text("\n".join(lines)+"\n",encoding="utf-8"); RESULT.write_text(json.dumps({"schema":"uruha_profile_answer_generalization_result_lock_v70","decision":report["decision"],"run_integrity_passed":report["run_integrity"]["passed"],"success_gates_passed":report["success_gates"]["passed"],"frozen_artifacts":{"preregistration":{"path":str(PREREG.relative_to(ROOT)),"sha256":sha(PREREG)},"dataset":{"path":str(DATASET.relative_to(ROOT)),"sha256":sha(DATASET)},"harness_lock":{"path":str(LOCK.relative_to(ROOT)),"sha256":sha(LOCK)},"raw":{"path":str(RAW.relative_to(ROOT)),"sha256":sha(RAW)},"analysis":{"path":str(ANALYSIS.relative_to(ROOT)),"sha256":sha(ANALYSIS)},"markdown":{"path":str(MD.relative_to(ROOT)),"sha256":sha(MD)}},"answer_path_shadow_authorized":report["success_gates"]["passed"] and report["run_integrity"]["passed"],"runtime_activation_authorized":False,"post_run_case_editing_authorized":False,"post_run_threshold_change_authorized":False,"evidence_boundary":report["evidence_boundary"]},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print(json.dumps({"decision":report["decision"],"integrity":report["run_integrity"],"metrics":report["metrics"],"pairwise":report["pairwise"],"gates":report["success_gates"]},ensure_ascii=False,indent=2))
if __name__=="__main__": main()
